print("gggggggggggg")
print("gggggggggggg")
print("gggggggggggg")
print("gggggggggggg")
print("gggggggggggg")
print("czzzzzzzzzzzzzzzz")
print("czzzzzzzzzzzzzzzz")
print("czzzzzzzzzzzzzzzz")
print("czzzzzzzzzzzzzzzz")
print("czzzzzzzzzzzzzzzz")

